### ISSUE TITLE
I'd like to change networks settings

### ISSUE THREAD

**Issue by mh-x** [xeniroio/snapscale-wallet-issues#1]
**Is your feature request related to a problem? Please describe.**
Currently I can change host ip of snapscale mainnet network but there is no way to save it.
<img width="549" alt="Screen Shot 2019-06-17 at 12 02 02 PM" src="https://user-images.githubusercontent.com/48746632/59577820-dcf6e280-90f7-11e9-8b99-1e2d36c016ff.png">

**Describe the solution you'd like**
I'd like to change existing network, add new network setting and remove existing network

**Comment by Miguel-Xeniro** [comment]
done
